# Generated by Django 4.2.30 on 2026-10-06 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('detected_language', models.CharField(blank=True, default='English', max_length=20)),
                ('is_voice_input', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ministry', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, help_text='Blank = national scheme', max_length=50)),
                ('sector', models.CharField(blank=True, choices=[('food_processing', 'Food Processing'), ('textiles_apparel', 'Textiles / Apparel'), ('beauty_wellness', 'Beauty & Wellness'), ('agriculture', 'Agriculture'), ('dairy', 'Dairy'), ('handicrafts', 'Handicrafts'), ('retail', 'Retail'), ('education', 'Education & Coaching'), ('technology', 'Technology & IT'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('sector_keywords', models.JSONField(default=list, help_text='List of sector keywords for matching')),
                ('business_types', models.JSONField(default=list)),
                ('target_groups', models.JSONField(default=list)),
                ('gender', models.CharField(choices=[('all', 'All'), ('female', 'Women Only'), ('male', 'Men Only')], default='all', max_length=10)),
                ('min_capital', models.BigIntegerField(blank=True, null=True)),
                ('max_capital', models.BigIntegerField(blank=True, null=True)),
                ('eligibility_text', models.TextField(blank=True)),
                ('benefits_text', models.TextField(blank=True)),
                ('documents_required', models.JSONField(default=list)),
                ('official_website', models.URLField(blank=True)),
                ('business_stages', models.JSONField(default=list, help_text='Applicable stages: idea, startup, growth, established')),
                ('active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True, help_text='Demo seed data, replace with verified production data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expertise', models.JSONField(default=list, help_text='List of expertise areas')),
                ('sectors', models.JSONField(default=list, help_text='Sectors they mentor in')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken')),
                ('state', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, default='Weekends', max_length=100)),
                ('contact_method', models.CharField(blank=True, max_length=200)),
                ('business_stages', models.JSONField(default=list)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('state', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('focus_areas', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('women_support', models.BooleanField(default=True)),
                ('entrepreneurship_support', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, choices=[('food_processing', 'Food Processing'), ('textiles_apparel', 'Textiles / Apparel'), ('beauty_wellness', 'Beauty & Wellness'), ('agriculture', 'Agriculture'), ('dairy', 'Dairy'), ('handicrafts', 'Handicrafts'), ('retail', 'Retail'), ('education', 'Education & Coaching'), ('technology', 'Technology & IT'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('healthcare', 'Healthcare'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capital', models.BigIntegerField(blank=True, null=True)),
                ('target_customers', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('business_stage', models.CharField(choices=[('idea', 'Idea / Pre-launch'), ('startup', 'Startup (< 1 year)'), ('growth', 'Growth (1–3 years)'), ('established', 'Established (3+ years)')], default='idea', max_length=30)),
                ('goal', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('required_support', models.JSONField(default=list)),
                ('raw_gemini_response', models.JSONField(default=dict)),
                ('is_vague', models.BooleanField(default=False)),
                ('follow_up_questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ideas.businessidea')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('rule_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_matches', to='ideas.businessidea')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.governmentscheme')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('idea', 'scheme')},
            },
        ),
        migrations.CreateModel(
            name='NGOMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_matches', to='ideas.businessidea')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.ngo')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('idea', 'ngo')},
            },
        ),
        migrations.CreateModel(
            name='MentorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_matches', to='ideas.businessidea')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.mentor')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('idea', 'mentor')},
            },
        ),
    ]
