"""Management command: seed_ideas_data — seeds schemes, mentors, and NGOs."""
from django.core.management.base import BaseCommand
from ideas.models import GovernmentScheme, Mentor, NGO


SCHEMES = [
    {
        'name': 'Pradhan Mantri Mudra Yojana (PMMY)',
        'description': 'Provides collateral-free micro loans up to ₹10 lakh to non-corporate, non-farm small and micro enterprises.',
        'ministry': 'Ministry of Finance, Government of India',
        'state': '', 'sector': 'other',
        'sector_keywords': ['micro enterprise', 'small business', 'startup', 'loan', 'women entrepreneur', 'self employment'],
        'business_types': ['any small/micro business'], 'target_groups': ['small entrepreneurs', 'women entrepreneurs'],
        'gender': 'all', 'min_capital': 0, 'max_capital': 1000000,
        'eligibility_text': 'Any Indian citizen with a business plan for a non-farm income-generating activity.',
        'benefits_text': 'Collateral-free loans: Shishu up to ₹50,000 | Kishore ₹50k–₹5L | Tarun ₹5–₹10L.',
        'documents_required': ['Aadhaar card', 'PAN card', 'Business plan', 'Bank statement'],
        'official_website': 'https://www.mudra.org.in',
        'business_stages': ['idea', 'startup', 'growth'],
    },
    {
        'name': 'Stand-Up India Scheme',
        'description': 'Facilitates bank loans between ₹10 lakh and ₹1 crore to SC/ST and women borrowers for greenfield enterprises.',
        'ministry': 'Ministry of Finance, Government of India',
        'state': '', 'sector': 'manufacturing',
        'sector_keywords': ['manufacturing', 'services', 'trading', 'women', 'new enterprise'],
        'business_types': ['manufacturing', 'services', 'trading'], 'target_groups': ['women entrepreneurs', 'SC/ST entrepreneurs'],
        'gender': 'female', 'min_capital': 1000000, 'max_capital': 10000000,
        'eligibility_text': 'Women or SC/ST borrowers above 18 years setting up a greenfield enterprise.',
        'benefits_text': 'Composite loan of ₹10 lakh to ₹1 crore covering 75% of project cost.',
        'documents_required': ['Aadhaar', 'PAN', 'Caste certificate', 'Project report'],
        'official_website': 'https://www.standupmitra.in',
        'business_stages': ['startup', 'growth'],
    },
    {
        'name': 'Mahila Udyam Nidhi Scheme (SIDBI)',
        'description': 'SIDBI scheme providing soft loans to women entrepreneurs for setting up or expanding small-scale industries.',
        'ministry': 'Small Industries Development Bank of India (SIDBI)',
        'state': '', 'sector': 'manufacturing',
        'sector_keywords': ['small scale', 'manufacturing', 'women enterprise', 'soft loan', 'industry'],
        'business_types': ['small-scale manufacturing', 'cottage industry'], 'target_groups': ['women entrepreneurs'],
        'gender': 'female', 'min_capital': 0, 'max_capital': 1000000,
        'eligibility_text': 'Women entrepreneurs setting up or expanding small-scale industrial units.',
        'benefits_text': 'Soft loans up to ₹10 lakh at reduced interest rate with repayment up to 10 years.',
        'documents_required': ['Identity proof', 'Address proof', 'Business plan', 'Bank statements'],
        'official_website': 'https://www.sidbi.in',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'TREAD Scheme (Trade Related Entrepreneurship for Women)',
        'description': 'Ministry of MSME scheme for women below poverty line. Provides credit via NGOs, training, and counselling.',
        'ministry': 'Ministry of MSME, Government of India',
        'state': '', 'sector': 'services',
        'sector_keywords': ['trade', 'service', 'below poverty line', 'NGO', 'women', 'skill', 'training', 'self help group'],
        'business_types': ['trade', 'services', 'small manufacturing'], 'target_groups': ['women below poverty line'],
        'gender': 'female', 'min_capital': 0, 'max_capital': 200000,
        'eligibility_text': 'Women below poverty line through registered NGOs.',
        'benefits_text': 'Government grant up to 30% of total project cost. Balance as loan via NGO.',
        'documents_required': ['BPL certificate', 'Aadhaar', 'NGO recommendation letter'],
        'official_website': 'https://msme.gov.in',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'Annapurna Scheme',
        'description': 'Designed for women in the food catering business. Provides loans for purchasing kitchen equipment.',
        'ministry': 'State Bank of India / Nationalized Banks',
        'state': '', 'sector': 'food_processing',
        'sector_keywords': ['food', 'catering', 'kitchen', 'cooking', 'tiffin', 'homemade food', 'snacks', 'women food business'],
        'business_types': ['food catering', 'homemade food', 'tiffin service'], 'target_groups': ['women in food business'],
        'gender': 'female', 'min_capital': 0, 'max_capital': 50000,
        'eligibility_text': 'Women who want to set up a food catering unit. Must have a guarantor.',
        'benefits_text': 'Loan up to ₹50,000 for kitchen equipment. Repayable in 36 monthly instalments.',
        'documents_required': ['Aadhaar', 'PAN', 'Guarantor details', 'Bank account'],
        'official_website': 'https://sbi.co.in',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'PM Vishwakarma Scheme',
        'description': 'Support scheme for artisans and craftspeople covering 18 traditional trades including weaving, pottery, tailoring, embroidery.',
        'ministry': 'Ministry of MSME, Government of India',
        'state': '', 'sector': 'handicrafts',
        'sector_keywords': ['artisan', 'craft', 'handicraft', 'weaving', 'pottery', 'tailoring', 'embroidery', 'traditional', 'skill'],
        'business_types': ['handicrafts', 'tailoring', 'weaving', 'pottery', 'embroidery'], 'target_groups': ['artisans', 'craftspeople'],
        'gender': 'all', 'min_capital': 0, 'max_capital': 300000,
        'eligibility_text': 'Artisans in 18 identified traditional trades. One member per family.',
        'benefits_text': 'Free toolkit worth ₹15,000. Skill training with ₹500/day stipend. Credit up to ₹3 lakh at 5% interest.',
        'documents_required': ['Aadhaar', 'Mobile number linked to Aadhaar', 'Bank account'],
        'official_website': 'https://pmvishwakarma.gov.in',
        'business_stages': ['idea', 'startup', 'growth'],
    },
    {
        'name': 'Startup India Seed Fund Scheme',
        'description': 'Provides financial assistance to startups for proof of concept, prototype development, and market entry.',
        'ministry': 'Ministry of Commerce & Industry, Government of India',
        'state': '', 'sector': 'technology',
        'sector_keywords': ['startup', 'innovation', 'technology', 'product', 'prototype', 'seed fund', 'incubator'],
        'business_types': ['tech startup', 'product startup', 'innovative business'], 'target_groups': ['startups', 'innovators'],
        'gender': 'all', 'min_capital': 0, 'max_capital': 5000000,
        'eligibility_text': 'DPIIT-recognized startups incorporated for less than 2 years.',
        'benefits_text': 'Up to ₹20 lakh grant for validation. Up to ₹50 lakh for market entry.',
        'documents_required': ['DPIIT startup certificate', 'Business plan', 'Founders KYC'],
        'official_website': 'https://www.startupindia.gov.in',
        'business_stages': ['startup', 'growth'],
    },
    {
        'name': 'Maharashtra Mahila Arthik Vikas Mahamandal (MAVIM)',
        'description': 'Maharashtra state corporation for economic empowerment of women through SHGs, skill training, micro-credit, and market linkages.',
        'ministry': 'Government of Maharashtra',
        'state': 'MH', 'sector': 'other',
        'sector_keywords': ['Maharashtra', 'SHG', 'self help group', 'micro credit', 'skill training', 'women empowerment', 'MAVIM'],
        'business_types': ['any small business', 'SHG activity'], 'target_groups': ['Maharashtra women', 'SHG members'],
        'gender': 'female', 'min_capital': 0, 'max_capital': 500000,
        'eligibility_text': 'Women in Maharashtra, especially rural and semi-urban areas.',
        'benefits_text': 'Micro-credit, skill development, market linkages, entrepreneurship training.',
        'documents_required': ['Aadhaar', 'SHG formation documents', 'Bank passbook'],
        'official_website': 'https://mavim.maharashtra.gov.in',
        'business_stages': ['idea', 'startup', 'growth'],
    },
    {
        'name': 'National Rural Livelihood Mission (NRLM) — Jeevika',
        'description': 'Supports rural women through Self-Help Groups with credit linkages, livelihood support, and skill training.',
        'ministry': 'Ministry of Rural Development, Government of India',
        'state': '', 'sector': 'agriculture',
        'sector_keywords': ['rural', 'SHG', 'self help group', 'livelihood', 'NRLM', 'agriculture', 'dairy', 'rural women'],
        'business_types': ['agriculture', 'dairy', 'rural micro-enterprise'], 'target_groups': ['rural women', 'BPL households'],
        'gender': 'female', 'min_capital': 0, 'max_capital': 600000,
        'eligibility_text': 'Rural women, priority to BPL households. Form or join an SHG.',
        'benefits_text': 'Revolving fund ₹15,000. Bank credit linkage up to ₹6 lakh. Skill training.',
        'documents_required': ['Aadhaar', 'SHG passbook', 'Ration card'],
        'official_website': 'https://aajeevika.gov.in',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'PM Formalization of Micro Food Processing Enterprises (PM-FME)',
        'description': 'Credit-linked subsidy for upgrading existing micro food processing units.',
        'ministry': 'Ministry of Food Processing Industries',
        'state': '', 'sector': 'food_processing',
        'sector_keywords': ['food processing', 'micro food', 'pickle', 'masala', 'snack', 'bakery', 'dairy product', 'millet', 'ragi'],
        'business_types': ['food processing', 'micro food unit', 'dairy', 'bakery', 'pickle'], 'target_groups': ['micro food processors'],
        'gender': 'all', 'min_capital': 0, 'max_capital': 1000000,
        'eligibility_text': 'Existing micro food processing units. New units under One District One Product (ODOP).',
        'benefits_text': 'Credit-linked subsidy 35% of project cost up to ₹10 lakh. Support for FSSAI, branding, packaging.',
        'documents_required': ['Aadhaar', 'Business proof', 'Bank statement', 'Project report'],
        'official_website': 'https://pmfme.mofpi.gov.in',
        'business_stages': ['startup', 'growth', 'established'],
    },
    {
        'name': 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
        'description': 'Skill training and placement program for rural youth including women. Covers 250+ trade courses.',
        'ministry': 'Ministry of Rural Development, Government of India',
        'state': '', 'sector': 'education',
        'sector_keywords': ['skill training', 'rural', 'placement', 'vocational', 'training', 'DDU-GKY', 'youth', 'course'],
        'business_types': ['skill-based services', 'vocational'], 'target_groups': ['rural youth 15-35 years', 'women'],
        'gender': 'all', 'min_capital': 0, 'max_capital': 0,
        'eligibility_text': 'Rural youth 15–35 years. Women and marginalized groups given priority.',
        'benefits_text': 'Free skill training. Placement assistance. Post-placement support.',
        'documents_required': ['Aadhaar', 'Age proof', 'Educational certificate'],
        'official_website': 'https://ddugky.gov.in',
        'business_stages': ['idea'],
    },
]

MENTORS = [
    {
        'name': 'Sunita Marathe',
        'expertise': ['Food Business', 'Packaging', 'Branding', 'FSSAI Compliance', 'Rural Entrepreneurship'],
        'sectors': ['food_processing', 'dairy', 'agriculture'],
        'languages': ['Marathi', 'Hindi', 'English'], 'state': 'MH', 'district': 'Pune',
        'experience_years': 12, 'availability': 'Weekends, online', 'contact_method': 'WhatsApp / Video Call',
        'bio': 'Former food technology consultant who has helped 50+ women launch home-based food businesses. Expert in FSSAI licensing, packaging design, and selling on Amazon/Flipkart.',
        'business_stages': ['idea', 'startup', 'growth'],
    },
    {
        'name': 'Priya Kulkarni',
        'expertise': ['Tailoring', 'Fashion Design', 'Boutique Management', 'Online Selling', 'Instagram Marketing'],
        'sectors': ['textiles_apparel', 'retail', 'handicrafts'],
        'languages': ['Marathi', 'Hindi', 'English'], 'state': 'MH', 'district': 'Nashik',
        'experience_years': 8, 'availability': 'Weekday evenings', 'contact_method': 'Phone / WhatsApp',
        'bio': 'Runs a successful boutique in Nashik with 300+ clients. Teaches tailoring entrepreneurship.',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'Rekha Sharma',
        'expertise': ['Digital Marketing', 'Social Media', 'E-commerce', 'Technology Startups'],
        'sectors': ['technology', 'retail', 'services', 'education'],
        'languages': ['Hindi', 'English'], 'state': 'DL', 'district': 'New Delhi',
        'experience_years': 10, 'availability': 'Flexible, online only', 'contact_method': 'Email / Video Call',
        'bio': 'Digital entrepreneur who built a women-focused e-commerce startup.',
        'business_stages': ['startup', 'growth'],
    },
    {
        'name': 'Kavitha Reddy',
        'expertise': ['Agriculture', 'Organic Farming', 'Farm-to-Market', 'SHG Leadership', 'Government Schemes'],
        'sectors': ['agriculture', 'food_processing', 'dairy'],
        'languages': ['Telugu', 'Hindi', 'English'], 'state': 'TG', 'district': 'Hyderabad',
        'experience_years': 15, 'availability': 'Monday–Friday mornings', 'contact_method': 'WhatsApp',
        'bio': 'Agricultural scientist turned entrepreneur. Helped 200+ rural women access NRLM and PM-FME benefits.',
        'business_stages': ['idea', 'startup', 'growth', 'established'],
    },
    {
        'name': 'Meera Iyer',
        'expertise': ['Beauty & Wellness', 'Salon Management', 'Bridal Services', 'Business Finance'],
        'sectors': ['beauty_wellness', 'services'],
        'languages': ['Tamil', 'English', 'Hindi'], 'state': 'TN', 'district': 'Chennai',
        'experience_years': 9, 'availability': 'Weekends', 'contact_method': 'Phone / WhatsApp',
        'bio': 'Owns a chain of 3 beauty salons in Chennai. Mentors women who want to start beauty businesses.',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'Anjali Patel',
        'expertise': ['Handicrafts', 'Export Market', 'Artisan Cooperatives', 'Etsy/Amazon Handmade', 'PM Vishwakarma'],
        'sectors': ['handicrafts', 'textiles_apparel', 'retail'],
        'languages': ['Gujarati', 'Hindi', 'English'], 'state': 'GJ', 'district': 'Ahmedabad',
        'experience_years': 11, 'availability': 'Tuesday and Thursday evenings', 'contact_method': 'WhatsApp',
        'bio': 'Helps artisan women sell on global platforms. Guided 80+ women to register under PM Vishwakarma.',
        'business_stages': ['startup', 'growth', 'established'],
    },
    {
        'name': 'Deepa Nair',
        'expertise': ['Dairy Business', 'Milk Cooperative', 'FSSAI', 'Cold Chain', 'Rural Women Entrepreneurship'],
        'sectors': ['dairy', 'food_processing', 'agriculture'],
        'languages': ['Malayalam', 'Hindi', 'English'], 'state': 'KL', 'district': 'Thrissur',
        'experience_years': 14, 'availability': 'Saturday mornings', 'contact_method': 'WhatsApp / Phone',
        'bio': 'Runs a women-led dairy cooperative with 120 members in Kerala.',
        'business_stages': ['idea', 'startup', 'growth'],
    },
    {
        'name': 'Fatima Khan',
        'expertise': ['Retail Shop', 'Inventory Management', 'GST & Accounting', 'MSME Registration'],
        'sectors': ['retail', 'services', 'manufacturing'],
        'languages': ['Urdu', 'Hindi', 'English'], 'state': 'UP', 'district': 'Lucknow',
        'experience_years': 7, 'availability': 'Weekday evenings online', 'contact_method': 'Video Call / WhatsApp',
        'bio': 'CA by qualification, entrepreneur by choice. Helps women with MSME registration and GST filing.',
        'business_stages': ['startup', 'growth', 'established'],
    },
    {
        'name': 'Sangeetha Krishnan',
        'expertise': ['Education Business', 'Online Tutoring', 'Ed-Tech', 'Coaching Centre', 'Curriculum Design'],
        'sectors': ['education', 'services', 'technology'],
        'languages': ['Tamil', 'English', 'Hindi'], 'state': 'TN', 'district': 'Coimbatore',
        'experience_years': 6, 'availability': 'Flexible', 'contact_method': 'Email / Video Call',
        'bio': 'Built an online tutoring platform serving 2000 students.',
        'business_stages': ['idea', 'startup'],
    },
    {
        'name': 'Varsha Joshi',
        'expertise': ['General Entrepreneurship', 'Business Planning', 'Fundraising', 'Women Leadership'],
        'sectors': ['other', 'services', 'retail', 'manufacturing'],
        'languages': ['Marathi', 'Hindi', 'English'], 'state': 'MH', 'district': 'Mumbai',
        'experience_years': 18, 'availability': 'By appointment', 'contact_method': 'LinkedIn / Email',
        'bio': 'Serial entrepreneur and angel investor. Has mentored 500+ women across all sectors.',
        'business_stages': ['idea', 'startup', 'growth', 'established'],
    },
]

NGOS = [
    {
        'name': "SEWA (Self Employed Women's Association)",
        'description': "India's largest union of informal women workers and micro-entrepreneurs.",
        'state': 'GJ', 'district': 'Ahmedabad',
        'focus_areas': ['women empowerment', 'self employment', 'micro finance', 'skill development'],
        'services': ['microfinance', 'skill training', 'cooperative formation', 'market linkages'],
        'languages': ['Gujarati', 'Hindi', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'info@sewa.org', 'website': 'https://www.sewa.org', 'verified': True,
    },
    {
        'name': 'Mahila Arthik Vikas Mandal (MAVM)',
        'description': 'Maharashtra-based NGO supporting women entrepreneurs through micro-credit and SHG formation.',
        'state': 'MH', 'district': 'Pune',
        'focus_areas': ['women entrepreneurship', 'micro credit', 'SHG', 'food processing', 'handicrafts'],
        'services': ['microfinance', 'SHG formation', 'business training', 'market linkages'],
        'languages': ['Marathi', 'Hindi'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'support@mavm.org', 'website': '', 'verified': False,
    },
    {
        'name': 'Udyogini',
        'description': 'National NGO providing comprehensive support to women micro-entrepreneurs across India.',
        'state': '', 'district': '',
        'focus_areas': ['women entrepreneurship', 'food processing', 'textiles', 'handicrafts', 'dairy', 'retail'],
        'services': ['business training', 'microfinance linkage', 'market access', 'technology support'],
        'languages': ['Hindi', 'English', 'Marathi', 'Gujarati'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'info@udyogini.org', 'website': 'https://www.udyogini.org', 'verified': True,
    },
    {
        'name': 'Stree Shakti Foundation',
        'description': 'Maharashtra NGO supporting rural and semi-urban women with skill development and SHG banking.',
        'state': 'MH', 'district': 'Nagpur',
        'focus_areas': ['women empowerment', 'skill development', 'government scheme assistance', 'SHG'],
        'services': ['skill training', 'scheme application support', 'SHG formation'],
        'languages': ['Marathi', 'Hindi'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'streeshakti@org.in', 'website': '', 'verified': False,
    },
    {
        'name': 'DHAN Foundation',
        'description': 'Tamil Nadu-based development organization focusing on community development and SHG programs.',
        'state': 'TN', 'district': 'Madurai',
        'focus_areas': ['agriculture', 'dairy', 'SHG', 'rural livelihoods'],
        'services': ['SHG support', 'agriculture support', 'microfinance', 'skill training'],
        'languages': ['Tamil', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'dhan@dhan.org', 'website': 'https://www.dhan.org', 'verified': True,
    },
    {
        'name': 'Rang De',
        'description': 'Social investment platform connecting impact investors with low-income women entrepreneurs.',
        'state': '', 'district': '',
        'focus_areas': ['micro credit', 'women entrepreneurship', 'financial inclusion', 'rural business'],
        'services': ['peer-to-peer lending', 'micro loans', 'financial literacy'],
        'languages': ['Hindi', 'English', 'Kannada', 'Tamil'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'support@rangde.in', 'website': 'https://rangde.in', 'verified': True,
    },
    {
        'name': 'Grameen Foundation India',
        'description': 'Provides digital financial services, agriculture support, and entrepreneurship programs.',
        'state': '', 'district': '',
        'focus_areas': ['digital financial services', 'agriculture', 'women health', 'entrepreneurship'],
        'services': ['digital literacy', 'financial services', 'agri-advisory', 'entrepreneurship training'],
        'languages': ['Hindi', 'English', 'Marathi', 'Gujarati', 'Odia'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'info@grameenfoundation.org', 'website': 'https://grameenfoundation.org', 'verified': True,
    },
    {
        'name': 'Craft Council of India',
        'description': 'Support organization for traditional artisans. Helps connect with markets and PM Vishwakarma registration.',
        'state': '', 'district': '',
        'focus_areas': ['handicrafts', 'artisan support', 'traditional craft', 'design', 'market linkages'],
        'services': ['design training', 'market access', 'exhibition support', 'export guidance'],
        'languages': ['Hindi', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'info@craftcouncil.in', 'website': 'https://craftcouncilofindia.org', 'verified': False,
    },
    {
        'name': 'iCreate (International Centre for Entrepreneurship)',
        'description': 'Gujarat-based entrepreneurship centre running women-focused bootcamps and incubation programs.',
        'state': 'GJ', 'district': 'Ahmedabad',
        'focus_areas': ['startup', 'innovation', 'technology', 'entrepreneurship training', 'incubation'],
        'services': ['incubation', 'mentoring', 'seed funding access', 'networking'],
        'languages': ['Gujarati', 'Hindi', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'info@icreate.org.in', 'website': 'https://www.icreate.org.in', 'verified': True,
    },
    {
        'name': 'Pradan (Professional Assistance for Development Action)',
        'description': 'Works with rural communities in Jharkhand, MP, Chhattisgarh. Builds SHGs for women livelihoods.',
        'state': 'JH', 'district': 'Ranchi',
        'focus_areas': ['rural livelihoods', 'SHG', 'agriculture', 'forest produce', 'dairy'],
        'services': ['SHG formation', 'livelihood training', 'micro-enterprise support'],
        'languages': ['Hindi', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'pradan@pradan.net', 'website': 'https://www.pradan.net', 'verified': True,
    },
    {
        'name': 'CHETNA',
        'description': 'Gujarat-based NGO focused on women and child health, nutrition, and livelihood programs.',
        'state': 'GJ', 'district': 'Ahmedabad',
        'focus_areas': ['agriculture', 'women health', 'tribal women', 'SHG', 'natural farming'],
        'services': ['SHG support', 'livelihood training', 'natural farming guidance'],
        'languages': ['Gujarati', 'Hindi', 'English'],
        'women_support': True, 'entrepreneurship_support': True,
        'contact': 'chetna@chetna.org', 'website': 'https://www.chetna.org', 'verified': True,
    },
]


class Command(BaseCommand):
    help = 'Seed database with government schemes, mentors, and NGOs for NariNiti'

    def handle(self, *args, **options):
        self.stdout.write('Seeding GovernmentScheme data...')
        created = 0
        for s in SCHEMES:
            _, c = GovernmentScheme.objects.get_or_create(name=s['name'], defaults={**s, 'is_demo': True})
            if c:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'  {created} schemes created ({len(SCHEMES)} total)'))

        self.stdout.write('Seeding Mentor data...')
        created = 0
        for m in MENTORS:
            _, c = Mentor.objects.get_or_create(name=m['name'], defaults={**m, 'is_demo': True})
            if c:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'  {created} mentors created ({len(MENTORS)} total)'))

        self.stdout.write('Seeding NGO data...')
        created = 0
        for n in NGOS:
            _, c = NGO.objects.get_or_create(name=n['name'], defaults={**n, 'is_demo': True})
            if c:
                created += 1
        self.stdout.write(self.style.SUCCESS(f'  {created} NGOs created ({len(NGOS)} total)'))

        self.stdout.write(self.style.SUCCESS('\nSeed complete! NariNiti database is ready.'))
